In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"A": ["a", "b", "a"], "B": ["b", "a", "c"], "C": [1, 2, 3]})

In [3]:
df

   A  B  C
0  a  b  1
1  b  a  2
2  a  c  3

In [5]:
df = pd.get_dummies(df, prefix=["col1", "col2"])

In [6]:
df

   C  col1_a  col1_b  col2_a  col2_b  col2_c
0  1    True   False   False    True   False
1  2   False    True    True   False   False
2  3    True   False   False   False    True

In [7]:
df = pd.DataFrame({'Color': ['Red', 'Green', 'Blue']})

In [8]:
df

   Color
0    Red
1  Green
2   Blue

In [11]:
df_encoded = pd.get_dummies(df)

In [12]:
df_encoded

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1       False         True      False
2        True        False      False